[package]
name = "calva-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renderer = { package = "calva-renderer", path = "../calva-renderer" }
epi = "0.15.0"
egui = "0.15.0"
egui_wgpu_backend = "0.15.0"
egui_winit_platform = "0.12.0"
winit = "0.26.0"
