[package]
name = "calva-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
renderer = { package = "calva-renderer", path = "../calva-renderer" }
thousands = "0.2"
egui = "0.20"
egui-wgpu = "0.20"
winit = "0.27"
