[workspace]
resolver = "2"
members = [
    "calva",
    "calva-gltf",
    "calva-renderer",
    "demo",
]

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
# wgpu = { git = "https://github.com/gfx-rs/wgpu.git", branch = "master" }
# wgpu = { path = "../wgpu/wgpu" }
# naga = { git = "https://github.com/gfx-rs/naga.git", branch = "master" }
# wgpu-profiler = { git = "https://github.com/IcanDivideBy0/wgpu-profiler.git", branch = "wgpu-0.15" }
# egui-wgpu = { path = "../egui/crates/egui-wgpu" }
# egui-winit = { path = "../egui/crates/egui-winit" }
# egui = { path = "../egui/crates/egui" }
# egui-wgpu = { git = "https://github.com/emilk/egui.git", branch = "master" }
# egui-winit = { git = "https://github.com/emilk/egui.git", branch = "master" }
# egui = { git = "https://github.com/emilk/egui.git", branch = "master" }

# [patch."https://github.com/gfx-rs/naga"]
# naga = { path = "../naga" }