[workspace]
resolver = "2"
members = [
    "calva",
    "calva-gltf",
    "calva-renderer",
    "demo",
]

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
wgpu = { path = "../wgpu/wgpu" }
egui_wgpu_backend = { path = "../egui_wgpu_backend" }
egui_winit_platform = { path = "../egui_winit_platform" }
