[workspace]
resolver = "2"
members = [
    "calva",
    "calva-egui",
    "calva-gltf",
    "calva-renderer",
    "demo",
]

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
gltf = { git = "https://github.com/IcanDivideBy0/gltf.git", branch = "joints_fixed_size_iterator" }
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", branch = "master" }
egui_wgpu_backend = { git = "https://github.com/IcanDivideBy0/egui_wgpu_backend.git", branch = "wgpu-0.13" }