[workspace]
resolver = "2"
members = [
    "calva",
    "calva-egui",
    "calva-gltf",
    "calva-renderer",
    "demo",
]

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
gltf = { git = "https://github.com/IcanDivideBy0/gltf.git", branch = "joints_fixed_size_iterator" }