[package]
name = "calva-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitflags = "1.3"
bytemuck = { version = "1.12", features = [ "derive" ] }
glam = { version = "0.23", features = ["bytemuck"] }
wgpu = "0.15"
wgpu-profiler = "0.11"
raw-window-handle = "0.5"
rand = "0.8"