[package]
name = "calva-renderer"
version = "0.1.0"
edition = "2021"

[features]
default = []
profiler = ["dep:wgpu-profiler"]

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.12", features = [ "derive" ] }
glam = { version = "0.23", features = ["bytemuck"] }
wgpu = "0.15"
wgpu-profiler = { version = "0.11", optional = true }
raw-window-handle = "0.5"
rand = "0.8"
