[package]
name = "calva-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calva = { path = "../calva" }
anyhow = "1.0.40"
async-std = { version = "1.10.0", features = ["attributes"] }
bytemuck = "1.7"
env_logger = "0.9.0"
glam = { version = "0.20.0", features = ["bytemuck"] }
winit = "0.26.0"
rand = "0.8.3"
image = "0.23.14"
